### ISSUE TITLE
Safari credit card autofill

### ISSUE THREAD

**Issue by unsignedint** [braintree/braintree-web#216]
Hi guys, we are integrating v3.3 of the Braintree client using Hosted Fields. It's generally working fine except for very annoying issues with Safari AutoFill (Safari 10.0 on macOS 10.12).

See the following screenshot, using the demo form on the Hosted Fields demo page. So basically I have selected a card to fill and it has chopped the last three digits:

<img width="939" alt="screen shot 2016-09-23 at 3 43 10 pm" src="https://cloud.githubusercontent.com/assets/929353/18773670/577f6cf8-81a5-11e6-924e-fdbbdb5c6b7e.png">

From this point on, attempting to autofill again does weird things, and submitting the form obviously fails. Moreover, expiry date is missing which would be cool to autofill, too.

I'm surprised nobody else seems to have reported this problem (as far as I can tell).. so if its an issue with my setup please advise!

**Comment by mrak** [comment]
Thanks for the report. We've added this to our internal tracker.

**Comment by zineer** [comment]
Also seeing this issue on OSX 10.11.6 and Safari 9.1.6. It doesn't just cut off the last 3 digits, but instead skips numbers where the code puts spaces in. So if my card is 1234 1234 1234 1234, after Safari auto-fills, you end up with 1234 2341 3412 4.

On iOS 10, Safari's auto-fill doesn't replace the placeholder text, but the background of the card still updates to show it recognized the card was mastercard.

**Comment by unsignedint** [comment]
I guess this didn't make it in 3.4.0; any update on progress? I'm actually surprised there are no other people complaining about it!

**Comment by Karl-Janzon** [comment]
Saw this issue with other autofill plugins as well. With Dashlane I just got the exp. date repeated in each field. With roboform nothing.

**Comment by JerseyCo** [comment]
We've had customers complain they can't process orders and upon investigation found they are all using Safari on a Mac - the card autofill seems to be a problem. Is there an ETA on a fix? Thanks

**Comment by crookedneighbor** [comment]
We're still investigating possible solutions for this. We do not have an ETA.

Safari does not emit an event when autofill takes place, so it is difficult to write a workaround for it. 

In the meantime, you can always disable formatting for each field if you detect that the user is using Safari.

http://braintree.github.io/braintree-web/current/module-braintree-web_hosted-fields.html

```js
function isSafari () { /* logic to detect safari */ }

var shouldFormat = !isSafari();

braintree.hostedFields.create({
  client: clientInstance,
  styles: {
    // your styles here
  },
  fields: {
    number: {
      selector: '#card-number',
      formatInput: shouldFormat
    },
    cvv: {
      selector: '#cvv',
      placeholder: '•••',
      formatInput: shouldFormat
    },
    // etc
  }
}, callback);
```

**Comment by davidEthika** [comment]
On top of this safari issue, @crookedneighbor It appears that viewing hosted fields on chrome, you can't even select a previously saved card, the same popup that appears on safari to select a card, doesn't show up on chrome.

**Comment by gerryhigh** [comment]
It's not just a Safari issue. I'm seeing it with my users on both Chrome & Safari. Not sure yet about other browsers. I'd say this is a major, major issue. I've started logging errors and have seen a couple thousand errors logged in what appears to be related to this issue.

I saw it in action tonight by a user who was having the issue on their Android 6.0.1 phone (Chrome 54). They input the credit card correctly but it didn't format (e.g. no spaces between the numbers).  As a side note the expiration date did format with a slash (e.g. mm/yy).  Then on the call to tokenize the card it failed. The following was returned:
{
  "name": "BraintreeError",
  "code": "HOSTED_FIELDS_FIELDS_INVALID",
  "message": "Some payment input fields are invalid. Cannot tokenize invalid card fields.",
  "type": "CUSTOMER",
  "details": {
    "invalidFieldKeys": ["number"]
  }
}

So then if I clicked on the CC field and backspaced it suddenly tried to format. But it did it incorrectly. For example, say I input a card like this:

4123456789012345

and backspaced on the 5 it would then become

4123 4567 8901 345 (or something like that). I had to jack around with the card number and type very carefully to eventually get it to work. Note that on this Android device it was using a numeric only keyboard for the input field and thus I couldn't input spaces. The user was also Spanish speaking and thus had Spanish set as the default language.

I think I wound up entering an invalid 13th character since I knew that was going to get deleted.

So instead of
4123456789012345
I input
4123456789012234

After backspacing it became (I think)
4123 4567 8901 234 and then I was able to type the 5 (actually it was more complicated then this but you get the idea) and then submit the card and the payment worked.

Did I say this is a major issue? Are you telling me that if I turn off formatting for both Chrome & Safari this might work?

I'm going to turn off formatting on the CC field to see if I can get this working. As a side note I'm using version 3.4 of the API.

I can not easily go back to the 2.x API as I'm using Apple Pay for Web. So I'm stuck for now and needing a fix.

**Comment by crookedneighbor** [comment]
We've made progress on the Safari Autofill issue. See https://github.com/braintree/restricted-input/pull/19 for the changes to our formatter.

It will be fixed in the next release of braintree-web.

@gerryhigh We'll have to do more investigation regarding your reported issue about Chrome on Android. 

Turning off formatting for that field will treat the inputs as regular text inputs, so it should work as you expect.

**Comment by gerryhigh** [comment]
@crookedneighbor FYI - I just want to make it clear that the issue I've seen isn't just Chrome on Android. The list is below:

Chrome--Android (various versions); Windows 7,8,10
Safari-iOS (various versions); Mac (various versions)
Samsung Internet 2.1 (Android 5.0, 5.1.1)
Chrome Mobile (28.0.1500, 53.0.2785, 54.0.2840)

I've turned off formatting on the card number field and it seems to be working better.  However, I've seen a couple of instances logged on Windows 10 (Chrome 54) and mac OS X 10.9.5 (Safari 9.1.2) but perhaps those are truly due to bad card input. I'll keep monitoring this.

As a side note, with this being such a critical issue the safer thing would have been for the SDK to have defaulted the value for formatting to be false.

**Comment by crookedneighbor** [comment]
The Safari Autofill issue is fixed on Macs with version `3.6.0`. We're still investigating it on iOS as well as the other reported browsers.

**Comment by crookedneighbor** [comment]
We've figured out the issue with Safari iOS autocomplete and the fix will be out in the next release. I'll update here when it's been published.

**Comment by dedman** [comment]
Hey @crookedneighbor thanks for the release. Safari CC autofill for the card numbers is working for me now. However it still isn't working for expiry date, do you have a separate ticket for that?

**Comment by crookedneighbor** [comment]
That's a tricky problem. Here's the deal.

In most browsers, for credit card autofill to work, you need multiple credit card fields. IE, the number and expiration date, etc. Safari is a little different in that it will prompt for autofill with just the credit card number.

That's why Safari will prompt for the number while other browsers will not, because in the context of the Hosted Field iframe, there is _just_ the credit card number input. However, that is also why the expiration date is not being populated, because although it looks like it's on the same form on your page, the input is actually isolated in the Hosted Fields iframe, so it doesn't have access to the other inputs.

There _may_ be a way to populate the other card fields by having dummy inputs for each credit card field in each iframe to capture that data, but it may wreak havoc with screen readers (IE, what happens when the screen reader sees many duplicate card fields on a page), so we will need to be very careful before we implement something like that.

**Comment by dedman** [comment]
@crookedneighbor thanks for the response, I appreciate it will take some time to work through the issues. The hosted fields solution is pretty awesome, and will be even better once you get these minor sort of things sorted out. Thanks for your work!

**Comment by kevinconroy** [comment]
I'll just add a +1 here that this issue has impacted a large number of our customers today and it took a while to figure out the root cause. We are keen to see the fix released for Safari, Android, and all of the major platforms that use auto-fill and copy and paste or drag and drop.

**Comment by EvanHahn** [comment]
This is fixed for Safari in `braintree-web@3.6.1`.

**Comment by EvanHahn** [comment]
Because this is fixed in Safari, we're going to close this issue.

Braintree is tracking other browsers' autofill bugs internally, but feel free to open new issues for other autofill problems. (I see Dashlane, Roboform, and Chrome mentioned in comments above.)

Thanks to everyone for their help on this!

**Comment by unsignedint** [comment]
Cool, thanks for all your work on that! However, would it be possible to get Expiry Date autocomplete working too?

**Comment by IvanIvanerov** [comment]
no.
Unfortunately.
And our program team tell me - «this is problem on braintree-side»

**Comment by dedman** [comment]
Hey @EvanHahn did you close this issue because autofill for expiry date is also complete? If its not complete would you like me to open a new ticket for it? I know it will be complicated to implement, but its not really feasible to not have a solution at all.

**Comment by crookedneighbor** [comment]
@dedman Yes, please open a new issue. This issue was for Safari mangling the credit card number input when using autofill. You can read my [explanation for why Safari allows autofill at all with hosted fields when other browsers do not here](https://github.com/braintree/braintree-web/issues/216#issuecomment-261617197).

We'll see what we can do, but as I stated before:

> There may be a way to populate the other card fields by having dummy inputs for each credit card field in each iframe to capture that data, but it may wreak havoc with screen readers (IE, what happens when the screen reader sees many duplicate card fields on a page), so we will need to be very careful before we implement something like that.

**Comment by unsignedint** [comment]
Title is "credit card autofill". Credit card is obviously a number, expiry
date, and CVV :)

**Comment by AlanApter** [comment]
@crookedneighbor Is there any update on IOS devices?

I saw your comment here - https://github.com/braintree/braintree-web/issues/216#issuecomment-260776414 and was wondering if there has since been any progress.

**Comment by AlanApter** [comment]
Additionally, if it was fixed, was IOS-Safari fixed in v3.6.3 or v3.6.2? I'm trying to validate whether we need to upgrade

**Comment by crookedneighbor** [comment]
This particular problem should have been fixed in [v3.6.1](https://github.com/braintree/braintree-web/blob/master/CHANGELOG.md#361), but I recommend upgrading to the latest version, v3.7.0.

@AlanApter If the number input is still being mangled, can you please provide the device and iOS version that it is happening on?

**Comment by AlanApter** [comment]
Unfortunately the complaints came from customers, not our QA team. We upgraded to the latest version and haven't had complaints since then, thanks for the help.

**Comment by crookedneighbor** [comment]
:+1:

**Comment by crookedneighbor** [comment]
3.18.0 is now out which includes fixes for autofill. 

If you'd like to see the code for the fix, you can look at [this file](https://github.com/braintree/braintree-web/commit/9011235f6b12399c1d5744f163eed581b5deb607#diff-21173be434c6b00816b3fbdb819ea2d6). Essentially we had to insert a form and the other inputs into the number iframe. When the autofill values populate, the iframe post messages out the expiration date (and in the case of LastPass, cvv) to the other iframes.

Tested on Google Chrome, Safari, LastPass, 1Password, Dashlane.

Firefox does not have a built in credit card manager.
