### ISSUE TITLE
Drop-In "MM / YY" field with Android FireFox 34.0

### ISSUE THREAD

**Issue by CheapData** [braintree/braintree-web#6]
Entered “Expiration Date” field value is incorrect, digits for YY are inverted

Steeps to reproduce: 
1. User need to enter expiration date "10 / 17" and type "1017"
2. "MM / YY" value is set to "10 / 71"

**Comment by EvanHahn** [comment]
If I'm not mistaken, we fixed this with a recent commit where we added special behavior for Android Firefox. @kyledetella, can you verify?

**Comment by CheapData** [comment]
No, it is not fixed. Current FireFox version for Android is 36 and it is the same buggy behavior for issuers #6 and #7. 
Actually, it is getting even worse. Now Drop-in extremely slow on FireFox while it is ok with Chrome on the same Galaxy Note.

**Comment by kyledetella** [comment]
This fix has not been released yet. It will be out in the next day or so. I will mention it here when it is out.

**Comment by kyledetella** [comment]
@CheapData as mentioned in #8, this has been addressed in `v2.5.3`.

**Comment by CheapData** [comment]
Confirmed
